### ISSUE TITLE
Backend roadmap for making moggie 1.0 possible

### ISSUE THREAD

**Issue by BjarniRunar** [BjarniRunar/moggie#6]
This expands on the moggie 1.0 section of Issue #1, taking the list of user-visible feature goals, and mapping them to back-end capabilities and API endpoints / CLI tools.

Basic non-networked features:

   - Read local (mbox, Maildir) email
       - [ ] moggie search mailbox:/path/to/file/...
   - Handle attachments
       - [ ] moggie.storage.files
       - [ ] moggie.email.parsemime
       - [ ] moggie parse 
   - Delete email from local (mbox, Maildir) mailboxes
       - [ ] moggie.storage.files
       - [ ] moggie delete
   - Move email from one mailbox to another
       - [ ] moggie.storage.files
       - [ ] moggie move, moggie copy ?
   - Notify user that new mail has arrived
       - [ ] moggie.workers.remote - IMAP IDLE support
       - [ ] moggie new
   - Add messages to a search engine
       - [ ] moggie.workers.importer
       - [ ] moggie import
       - [ ] moggie new
   - Allow user to search for mail
       - [ ] moggie.workers.search
       - [ ] moggie search 
   - Handle message threads correctly
       - [ ] moggie.email.metadata
       - [ ] moggie search
       - [ ] moggie parse
   - Display HTML and text content
       - [ ] moggie.security.html
       - [ ] moggie parse
       - [ ] moggie show
   - Compose
       - [ ] moggie address - for address autocompletion
       - [ ] moggie email
   - Reply
       - [ ] moggie email --forward
       - [ ] moggie reply
   - Forward
       - [ ] moggie email --forward
       - [ ] moggie forward
   - Send (local sendmail)
       - [ ] moggie.util.sendmail
       - [ ] moggie email --send-via
       - [ ] moggie send in:outbox
   - Tag / untag emails manually
       - [ ] moggie tag
   - Tag / untag emails automatically (manual filters and bayesian)
       - [ ] moggie.search.filters
       - [ ] moggie filter

Networking capabilities:

   - Read remote (IMAP, POP3) email
       - [ ] moggie.workers.remote
   - Delete / move email from remote (IMAP, POP3) mailboxes
       - [ ] moggie.workers.remote
       - [ ] moggie delete
       - [ ] moggie move
   - Send (SMTP/submission)
       - [ ] moggie.util.sendmail
       - [ ] moggie email --send-via
       - [ ] moggie send
